baseURL = "https://matthewcchan.github.io"
title   = "Matthew C. Chan"
languageCode = "en-us"
theme = "hello-friend-ng"


[params]
    # Directory name of your blog content (default is `content/posts`)
    contentTypeName = ""
    
    # Default theme "light" or "dark"
    # defaultTheme = "light"

    # Enable theme toggle
    # This options enables the theme toggle for the theme. 
    # The theme is respecting the prefers-color-scheme of the operating systeme. 
    # With this option on, the page user is able to set the scheme he wants. 
    enableThemeToggle = true

    homeSubtitle = "Mahan Postdoctoral Fellow | Fred Hutchinson Cancer Research Center"
    backgroundImage = "img/SERT_blender_cover_alpha.png"



    [params.logo]
        logoText = "/home/matthew c chan"
        logoHomeLink = "/"
        logoMark     = "$"
        
        # Set true to remove the logo cursor entirely.
        # logoCursorDisabled = false
        
        # Set to a valid CSS color to change the cursor in the logo.
        # logoCursorColor    = "#096feb"
        
        # Set to a valid CSS time value to change the animation duration, "0s" to disable.
        # logoCursorAnimate  = "2s"



    [[params.social]]
        name = "googlescholar"
        url = "https://scholar.google.com/citations?user=hpHJn5QAAAAJ&hl=en/"

    [[params.social]]
        name = "twitter"
        url = "https://twitter.com/mattcchan/"

    [[params.social]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/matthew-c-chan-0/"

    [[params.social]]
        name = "github"
        url = "https://github.com/matthewcchan/"

    [[params.social]]
        name = "orcid"
        url = "https://orcid.org/0000-0002-9826-1983"

    [[params.social]]
        name = "email"
        url = "mailto:mc26@illinois.edu"


[menu]
    [[menu.main]]
        identifier = "about"
        name       = "About"
        url        = "/about"
        weight     = 10    

    [[menu.main]]
        identifier = "cv"
        name       = "CV"
        url        = "/cv"
        weight     = 20

    [[menu.main]]
        identifier = "publications"
        name       = "Publications"
        url        = "/publications"
        weight     = 40

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"